# Generated by Django 6.1 on 2026-08-14 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensajedivision',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='mensajes_division/'),
        ),
        migrations.AddField(
            model_name='noticia',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='noticias/'),
        ),
    ]
